import logging
from typing import Optional

import requests

from ..config import settings

logger = logging.getLogger(__name__)


def build_notes_prompt(
    transcript: str,
    title: str,
    course: Optional[str],
    lecturer: Optional[str],
    lecture_date: Optional[str],
) -> str:
    """
    Build a clear prompt for the local LLM to convert a lecture transcript
    into structured, exam-focused notes.
    """
    # Format date to dd-mm-yyyy if provided
    formatted_date = lecture_date
    if lecture_date:
        try:
            from datetime import datetime
            # Try parsing common date formats
            for fmt in ["%Y-%m-%d", "%d-%m-%Y", "%m/%d/%Y", "%d/%m/%Y"]:
                try:
                    date_obj = datetime.strptime(lecture_date, fmt)
                    formatted_date = date_obj.strftime("%d-%m-%Y")
                    break
                except ValueError:
                    continue
        except Exception:
            formatted_date = lecture_date  # Keep original if parsing fails
    
    meta_lines = [f"Title: {title}"]
    if course:
        meta_lines.append(f"Course: {course}")
    if lecturer:
        meta_lines.append(f"Lecturer: {lecturer}")
    if formatted_date:
        meta_lines.append(f"Date: {formatted_date}")

    metadata_str = "\n".join(meta_lines)

    prompt = f"""
You are a highly accurate academic teaching assistant.

Your job is to transform a raw lecture transcript into clean, structured, exam-ready lecture notes.
Focus ONLY on information explicitly stated or clearly implied in the transcript.

### CRITICAL: You MUST start your notes with this exact metadata header (no dashes):
Title: {title}
{"Course: " + course if course else ""}
{"Lecturer: " + lecturer if lecturer else ""}
{"Date: " + formatted_date if formatted_date else ""}

### STRICT RULES (IMPORTANT):
- ALWAYS include the metadata header above at the very top of your notes
- Do NOT use markdown symbols like **, ##, ###, ---, etc.
- Use PLAIN TEXT ONLY with proper formatting and indentation
- Do NOT invent, assume, or hallucinate any information
- If something is unclear or incomplete in the transcript, OMIT it
- Ignore filler words, repetitions, speech errors, and off-topic chatter
- Do NOT explain that you are summarizing or analyzing — just produce notes
- Do NOT include commentary, apologies, or meta text

### NOTES STYLE GUIDELINES:
- After the metadata header, begin with a 2-3 sentence high-level overview of the lecture
- Organize content using UPPERCASE section headings (no # symbols)
- Use bullet points (-) under each heading
- Use ALL CAPS for emphasis instead of bold
- Keep language concise, factual, and suitable for exam revision
- Use English only

### REQUIRED STRUCTURE:
After metadata and overview, use this structure where applicable:
1. INTRODUCTION
2. KEY CONCEPTS
3. EXAMPLES / APPLICATIONS
4. SUMMARY

(If a section is not supported by the transcript, skip it.)

### OUTPUT FORMAT:
- Plain text only (NO markdown symbols)
- Section headings in UPPERCASE
- Bullet points using "-"
- Use blank lines to separate sections
- No paragraphs longer than 3 lines

### Lecture Transcript (verbatim)
\"\"\"
{transcript}
\"\"\"

Produce the final lecture notes now.
"""
    return prompt.strip()


def generate_notes_with_ollama(
    transcript: str,
    title: str,
    course: Optional[str],
    lecturer: Optional[str],
    lecture_date: Optional[str],
) -> str:
    """
    Call a local Ollama server to generate lecture notes from a transcript.

    Assumes Ollama is running and the configured model is available.
    """
    prompt = build_notes_prompt(transcript, title, course, lecturer, lecture_date)

    url = f"{settings.LLM_API_BASE_URL}/api/generate"
    payload = {
        "model": settings.LLM_MODEL_NAME,
        "prompt": prompt,
        "stream": False,
    }

    logger.info(
        "Requesting notes from Ollama model '%s' at '%s'...",
        settings.LLM_MODEL_NAME,
        url,
    )

    try:
        response = requests.post(url, json=payload, timeout=600)
        response.raise_for_status()
        data = response.json()
        notes_text = data.get("response", "").strip()
        if not notes_text:
            raise RuntimeError("Received empty notes from LLM.")
        logger.info("Notes successfully generated by LLM.")
        return notes_text
    except Exception as exc:  # broad for robustness, logged for debugging
        logger.exception("Failed to generate notes via LLM: %s", exc)
        raise

